[2021-07-20 16:17:57,206] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: trigger_rule.task1 2021-07-20T16:17:55.525669+00:00 [queued]>
[2021-07-20 16:17:57,268] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: trigger_rule.task1 2021-07-20T16:17:55.525669+00:00 [queued]>
[2021-07-20 16:17:57,269] {taskinstance.py:1067} INFO - 
--------------------------------------------------------------------------------
[2021-07-20 16:17:57,269] {taskinstance.py:1068} INFO - Starting attempt 1 of 1
[2021-07-20 16:17:57,273] {taskinstance.py:1069} INFO - 
--------------------------------------------------------------------------------
[2021-07-20 16:17:57,310] {taskinstance.py:1087} INFO - Executing <Task(BashOperator): task1> on 2021-07-20T16:17:55.525669+00:00
[2021-07-20 16:17:57,334] {standard_task_runner.py:52} INFO - Started process 9107 to run task
[2021-07-20 16:17:57,360] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'trigger_rule', 'task1', '2021-07-20T16:17:55.525669+00:00', '--job-id', '226', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/trigger_rule.py', '--cfg-path', '/tmp/tmplfan77af', '--error-file', '/tmp/tmphs5pzn8x']
[2021-07-20 16:17:57,366] {standard_task_runner.py:77} INFO - Job 226: Subtask task1
[2021-07-20 16:17:57,534] {logging_mixin.py:104} INFO - Running <TaskInstance: trigger_rule.task1 2021-07-20T16:17:55.525669+00:00 [running]> on host airflowvm
[2021-07-20 16:17:57,791] {taskinstance.py:1280} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=trigger_rule
AIRFLOW_CTX_TASK_ID=task1
AIRFLOW_CTX_EXECUTION_DATE=2021-07-20T16:17:55.525669+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2021-07-20T16:17:55.525669+00:00
[2021-07-20 16:17:57,805] {subprocess.py:52} INFO - Tmp dir root location: 
 /tmp
[2021-07-20 16:17:57,807] {subprocess.py:63} INFO - Running command: ['bash', '-c', 'exit 1']
[2021-07-20 16:17:57,842] {subprocess.py:75} INFO - Output:
[2021-07-20 16:17:57,847] {subprocess.py:83} INFO - Command exited with return code 1
[2021-07-20 16:17:57,880] {taskinstance.py:1481} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/sandbox/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1137, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/home/airflow/sandbox/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1311, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/home/airflow/sandbox/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1341, in _execute_task
    result = task_copy.execute(context=context)
  File "/home/airflow/sandbox/lib/python3.8/site-packages/airflow/operators/bash.py", line 180, in execute
    raise AirflowException('Bash command failed. The command returned a non-zero exit code.')
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code.
[2021-07-20 16:17:57,884] {taskinstance.py:1524} INFO - Marking task as FAILED. dag_id=trigger_rule, task_id=task1, execution_date=20210720T161755, start_date=20210720T161757, end_date=20210720T161757
[2021-07-20 16:17:57,935] {local_task_job.py:151} INFO - Task exited with return code 1
