[2021-07-15 19:08:50,016] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: user_processing.creating_table 2021-07-14T00:00:00+00:00 [queued]>
[2021-07-15 19:08:50,025] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: user_processing.creating_table 2021-07-14T00:00:00+00:00 [queued]>
[2021-07-15 19:08:50,025] {taskinstance.py:1067} INFO - 
--------------------------------------------------------------------------------
[2021-07-15 19:08:50,026] {taskinstance.py:1068} INFO - Starting attempt 1 of 1
[2021-07-15 19:08:50,027] {taskinstance.py:1069} INFO - 
--------------------------------------------------------------------------------
[2021-07-15 19:08:50,047] {taskinstance.py:1087} INFO - Executing <Task(SqliteOperator): creating_table> on 2021-07-14T00:00:00+00:00
[2021-07-15 19:08:50,050] {standard_task_runner.py:52} INFO - Started process 12249 to run task
[2021-07-15 19:08:50,059] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'user_processing', 'creating_table', '2021-07-14T00:00:00+00:00', '--job-id', '17', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/user_processing.py', '--cfg-path', '/tmp/tmpthy_b2kw', '--error-file', '/tmp/tmpvhq97lda']
[2021-07-15 19:08:50,061] {standard_task_runner.py:77} INFO - Job 17: Subtask creating_table
[2021-07-15 19:08:50,122] {logging_mixin.py:104} INFO - Running <TaskInstance: user_processing.creating_table 2021-07-14T00:00:00+00:00 [running]> on host airflowvm
[2021-07-15 19:08:50,185] {taskinstance.py:1280} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=user_processing
AIRFLOW_CTX_TASK_ID=creating_table
AIRFLOW_CTX_EXECUTION_DATE=2021-07-14T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-07-14T00:00:00+00:00
[2021-07-15 19:08:50,186] {sqlite.py:63} INFO - Executing: 
            CREATE TABLE users(
                firstname TEXT NOT NULL,
                lastname TEXT NOT NULL,
                country TEXT NOT NULL,
                username TEXT NOT NULL,
                password TEXT NOT NULL,
                email TEXT NOT NULL PRIMARY KEY
            );
            
[2021-07-15 19:08:50,191] {base.py:69} INFO - Using connection to: id: db_sqlite. Host: /home/airflow/airflow/airflow.db, Port: None, Schema: , Login: , Password: None, extra: {}
[2021-07-15 19:08:50,192] {dbapi.py:204} INFO - Running statement: 
            CREATE TABLE users(
                firstname TEXT NOT NULL,
                lastname TEXT NOT NULL,
                country TEXT NOT NULL,
                username TEXT NOT NULL,
                password TEXT NOT NULL,
                email TEXT NOT NULL PRIMARY KEY
            );
            , parameters: []
[2021-07-15 19:08:50,195] {taskinstance.py:1481} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/sandbox/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1137, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/home/airflow/sandbox/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1311, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/home/airflow/sandbox/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1341, in _execute_task
    result = task_copy.execute(context=context)
  File "/home/airflow/sandbox/lib/python3.8/site-packages/airflow/providers/sqlite/operators/sqlite.py", line 65, in execute
    hook.run(self.sql, parameters=self.parameters)
  File "/home/airflow/sandbox/lib/python3.8/site-packages/airflow/hooks/dbapi.py", line 184, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/sandbox/lib/python3.8/site-packages/airflow/hooks/dbapi.py", line 208, in _run_command
    cur.execute(sql_statement)
sqlite3.OperationalError: table users already exists
[2021-07-15 19:08:50,214] {taskinstance.py:1524} INFO - Marking task as FAILED. dag_id=user_processing, task_id=creating_table, execution_date=20210714T000000, start_date=20210715T190850, end_date=20210715T190850
[2021-07-15 19:08:50,272] {local_task_job.py:151} INFO - Task exited with return code 1
