[2021-07-21 04:52:39,444] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: elasticsearch_dag.connections_to_es 2021-07-21T04:52:36.647486+00:00 [queued]>
[2021-07-21 04:52:39,475] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: elasticsearch_dag.connections_to_es 2021-07-21T04:52:36.647486+00:00 [queued]>
[2021-07-21 04:52:39,475] {taskinstance.py:1067} INFO - 
--------------------------------------------------------------------------------
[2021-07-21 04:52:39,476] {taskinstance.py:1068} INFO - Starting attempt 1 of 1
[2021-07-21 04:52:39,476] {taskinstance.py:1069} INFO - 
--------------------------------------------------------------------------------
[2021-07-21 04:52:39,491] {taskinstance.py:1087} INFO - Executing <Task(PostgresToElasticOperator): connections_to_es> on 2021-07-21T04:52:36.647486+00:00
[2021-07-21 04:52:39,494] {standard_task_runner.py:52} INFO - Started process 7083 to run task
[2021-07-21 04:52:39,506] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'elasticsearch_dag', 'connections_to_es', '2021-07-21T04:52:36.647486+00:00', '--job-id', '278', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/elasticsearch_dag.py', '--cfg-path', '/tmp/tmptobcegyr', '--error-file', '/tmp/tmpeqehftud']
[2021-07-21 04:52:39,508] {standard_task_runner.py:77} INFO - Job 278: Subtask connections_to_es
[2021-07-21 04:52:39,631] {logging_mixin.py:104} INFO - Running <TaskInstance: elasticsearch_dag.connections_to_es 2021-07-21T04:52:36.647486+00:00 [running]> on host airflowvm
[2021-07-21 04:52:39,751] {taskinstance.py:1280} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=elasticsearch_dag
AIRFLOW_CTX_TASK_ID=connections_to_es
AIRFLOW_CTX_EXECUTION_DATE=2021-07-21T04:52:36.647486+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2021-07-21T04:52:36.647486+00:00
[2021-07-21 04:52:39,769] {base.py:69} INFO - Using connection to: id: elasticsearch_default. Host: localhost, Port: 9200, Schema: http, Login: None, Password: None, extra: {}
[2021-07-21 04:52:39,787] {base.py:69} INFO - Using connection to: id: ***_default. Host: localhost, Port: 5432, Schema: , Login: , Password: ***, extra: {'cursor': 'realdictcursor'}
[2021-07-21 04:52:39,804] {taskinstance.py:1481} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/sandbox/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1137, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/home/airflow/sandbox/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1311, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/home/airflow/sandbox/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1341, in _execute_task
    result = task_copy.execute(context=context)
  File "/home/airflow/airflow/plugins/elasticsearch_plugin/operators/postgres_to_elastic.py", line 30, in execute
    with closing(pg.get_conn()) as conn:
  File "/home/airflow/sandbox/lib/python3.8/site-packages/airflow/providers/postgres/hooks/postgres.py", line 115, in get_conn
    self.conn = psycopg2.connect(**conn_args)
  File "/home/airflow/sandbox/lib/python3.8/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: FATAL:  password authentication failed for user "airflow"
FATAL:  password authentication failed for user "airflow"

[2021-07-21 04:52:39,807] {taskinstance.py:1524} INFO - Marking task as FAILED. dag_id=elasticsearch_dag, task_id=connections_to_es, execution_date=20210721T045236, start_date=20210721T045239, end_date=20210721T045239
[2021-07-21 04:52:39,851] {local_task_job.py:151} INFO - Task exited with return code 1
