[2021-07-15 19:40:58,371] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: user_processing.is_api_available 2021-07-14T00:00:00+00:00 [queued]>
[2021-07-15 19:40:58,380] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: user_processing.is_api_available 2021-07-14T00:00:00+00:00 [queued]>
[2021-07-15 19:40:58,380] {taskinstance.py:1067} INFO - 
--------------------------------------------------------------------------------
[2021-07-15 19:40:58,381] {taskinstance.py:1068} INFO - Starting attempt 2 of 2
[2021-07-15 19:40:58,381] {taskinstance.py:1069} INFO - 
--------------------------------------------------------------------------------
[2021-07-15 19:40:58,395] {taskinstance.py:1087} INFO - Executing <Task(HttpSensor): is_api_available> on 2021-07-14T00:00:00+00:00
[2021-07-15 19:40:58,397] {standard_task_runner.py:52} INFO - Started process 14039 to run task
[2021-07-15 19:40:58,405] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'user_processing', 'is_api_available', '2021-07-14T00:00:00+00:00', '--job-id', '25', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/user_processing.py', '--cfg-path', '/tmp/tmprirgk84a', '--error-file', '/tmp/tmpy_4lwpwa']
[2021-07-15 19:40:58,406] {standard_task_runner.py:77} INFO - Job 25: Subtask is_api_available
[2021-07-15 19:40:58,451] {logging_mixin.py:104} INFO - Running <TaskInstance: user_processing.is_api_available 2021-07-14T00:00:00+00:00 [running]> on host airflowvm
[2021-07-15 19:40:58,499] {taskinstance.py:1280} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=user_processing
AIRFLOW_CTX_TASK_ID=is_api_available
AIRFLOW_CTX_EXECUTION_DATE=2021-07-14T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-07-14T00:00:00+00:00
[2021-07-15 19:40:58,500] {http.py:101} INFO - Poking: api/
[2021-07-15 19:40:58,505] {base.py:69} INFO - Using connection to: id: user_api. Host: https://randomuser.me/, Port: None, Schema: , Login: , Password: None, extra: {}
[2021-07-15 19:40:58,507] {http.py:140} INFO - Sending 'GET' to url: https://randomuser.me/api/
[2021-07-15 19:40:58,688] {base.py:243} INFO - Success criteria met. Exiting.
[2021-07-15 19:40:58,692] {taskinstance.py:1184} INFO - Marking task as SUCCESS. dag_id=user_processing, task_id=is_api_available, execution_date=20210714T000000, start_date=20210715T194058, end_date=20210715T194058
[2021-07-15 19:40:58,729] {taskinstance.py:1245} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2021-07-15 19:40:58,748] {local_task_job.py:151} INFO - Task exited with return code 0
