[2021-07-20 16:17:03,888] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: trigger_rule.task1 2021-07-20T16:17:02.188356+00:00 [queued]>
[2021-07-20 16:17:03,952] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: trigger_rule.task1 2021-07-20T16:17:02.188356+00:00 [queued]>
[2021-07-20 16:17:03,954] {taskinstance.py:1067} INFO - 
--------------------------------------------------------------------------------
[2021-07-20 16:17:03,955] {taskinstance.py:1068} INFO - Starting attempt 1 of 1
[2021-07-20 16:17:03,956] {taskinstance.py:1069} INFO - 
--------------------------------------------------------------------------------
[2021-07-20 16:17:03,981] {taskinstance.py:1087} INFO - Executing <Task(BashOperator): task1> on 2021-07-20T16:17:02.188356+00:00
[2021-07-20 16:17:03,986] {standard_task_runner.py:52} INFO - Started process 8978 to run task
[2021-07-20 16:17:04,024] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'trigger_rule', 'task1', '2021-07-20T16:17:02.188356+00:00', '--job-id', '224', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/trigger_rule.py', '--cfg-path', '/tmp/tmpr1cotazz', '--error-file', '/tmp/tmpnjche6ox']
[2021-07-20 16:17:04,029] {standard_task_runner.py:77} INFO - Job 224: Subtask task1
[2021-07-20 16:17:04,191] {logging_mixin.py:104} INFO - Running <TaskInstance: trigger_rule.task1 2021-07-20T16:17:02.188356+00:00 [running]> on host airflowvm
[2021-07-20 16:17:04,426] {taskinstance.py:1280} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=trigger_rule
AIRFLOW_CTX_TASK_ID=task1
AIRFLOW_CTX_EXECUTION_DATE=2021-07-20T16:17:02.188356+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2021-07-20T16:17:02.188356+00:00
[2021-07-20 16:17:04,428] {subprocess.py:52} INFO - Tmp dir root location: 
 /tmp
[2021-07-20 16:17:04,428] {subprocess.py:63} INFO - Running command: ['bash', '-c', 'exit 1']
[2021-07-20 16:17:04,457] {subprocess.py:75} INFO - Output:
[2021-07-20 16:17:04,469] {subprocess.py:83} INFO - Command exited with return code 1
[2021-07-20 16:17:04,505] {taskinstance.py:1481} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/sandbox/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1137, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/home/airflow/sandbox/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1311, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/home/airflow/sandbox/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1341, in _execute_task
    result = task_copy.execute(context=context)
  File "/home/airflow/sandbox/lib/python3.8/site-packages/airflow/operators/bash.py", line 180, in execute
    raise AirflowException('Bash command failed. The command returned a non-zero exit code.')
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code.
[2021-07-20 16:17:04,516] {taskinstance.py:1524} INFO - Marking task as FAILED. dag_id=trigger_rule, task_id=task1, execution_date=20210720T161702, start_date=20210720T161703, end_date=20210720T161704
[2021-07-20 16:17:04,602] {local_task_job.py:151} INFO - Task exited with return code 1
