[2021-07-15 19:42:34,115] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: user_processing.is_api_available 2020-01-01T00:00:00+00:00 [queued]>
[2021-07-15 19:42:34,123] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: user_processing.is_api_available 2020-01-01T00:00:00+00:00 [queued]>
[2021-07-15 19:42:34,124] {taskinstance.py:1067} INFO - 
--------------------------------------------------------------------------------
[2021-07-15 19:42:34,124] {taskinstance.py:1068} INFO - Starting attempt 2 of 1
[2021-07-15 19:42:34,124] {taskinstance.py:1069} INFO - 
--------------------------------------------------------------------------------
[2021-07-15 19:42:34,140] {taskinstance.py:1087} INFO - Executing <Task(HttpSensor): is_api_available> on 2020-01-01T00:00:00+00:00
[2021-07-15 19:42:34,143] {standard_task_runner.py:52} INFO - Started process 14135 to run task
[2021-07-15 19:42:34,153] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'user_processing', 'is_api_available', '2020-01-01T00:00:00+00:00', '--job-id', '31', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/user_processing.py', '--cfg-path', '/tmp/tmpek_ms4sh', '--error-file', '/tmp/tmpo32xz9r5']
[2021-07-15 19:42:34,154] {standard_task_runner.py:77} INFO - Job 31: Subtask is_api_available
[2021-07-15 19:42:34,211] {logging_mixin.py:104} INFO - Running <TaskInstance: user_processing.is_api_available 2020-01-01T00:00:00+00:00 [running]> on host airflowvm
[2021-07-15 19:42:34,267] {taskinstance.py:1280} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=user_processing
AIRFLOW_CTX_TASK_ID=is_api_available
AIRFLOW_CTX_EXECUTION_DATE=2020-01-01T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2020-01-01T00:00:00+00:00
[2021-07-15 19:42:34,269] {http.py:101} INFO - Poking: api/
[2021-07-15 19:42:34,274] {base.py:69} INFO - Using connection to: id: user_api. Host: https://randomuser.me/, Port: None, Schema: , Login: , Password: None, extra: {}
[2021-07-15 19:42:34,276] {http.py:140} INFO - Sending 'GET' to url: https://randomuser.me/api/
[2021-07-15 19:42:34,436] {base.py:243} INFO - Success criteria met. Exiting.
[2021-07-15 19:42:34,441] {taskinstance.py:1184} INFO - Marking task as SUCCESS. dag_id=user_processing, task_id=is_api_available, execution_date=20200101T000000, start_date=20210715T194234, end_date=20210715T194234
[2021-07-15 19:42:34,476] {taskinstance.py:1245} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2021-07-15 19:42:34,491] {local_task_job.py:151} INFO - Task exited with return code 0
